# **Web Scraping in Python**

For this lab, I am using Python and several Python libraries. The cells below will install these libraries when executed.

In [1]:
!mamba install bs4==4.10.0 -y
!pip install lxml==4.6.4
!mamba install html5lib==1.1 -y
# !pip install requests==2.26.0

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.15.3) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['bs4==4.10.0']

pkgs/r/linux-64          [<=>                 ] (00m:00s)
pkgs/r/linux-64          [=>              ] (00m:00s) 232 KB / ?? (767.62 KB/s)
pkgs/r/linux-64          [=>              ] (00m:00s) 232 KB / ?? (767.62 KB/s)
pkgs/r/noarch            [<=>                 ] (00m:00s)
pkgs/r/linux-64          [=>              ] (00m:00s) 232 KB / ?? (767.62 KB/s)
pkgs/r/noarch            [=>              ] (00m:00s) 232 KB / ?? (765.53 KB/s)
pkgs/r/linux-64          [=>              ] (00m:00s) 232 KB / ?? (767.62 KB/s)
pkgs/r/noarch            [=>              ] (00m:00s) 232 KB / ?? (765.53 KB/s)
pkgs/main/linux-64       [<=>                 ] (00m:00s)
pkgs/r/linux-64          [=>              ] (00m:00s) 232 KB / ?? (767.62 KB/s)
pkgs/r/noarch            [=>              ] (00m:00s) 232 KB / ?? (765.53 KB/s)
pkgs/main/linux-64       [=>              ] (00m:00s) 240 KB / ?? (789.60 KB/s)
pkgs/r/linux-64          [=>              ] (00m:00s) 232 KB / ?? (767.62 KB/s)
pkgs/r/noarch            [=>              ] (00m:00s) 232 KB / ?? (765.53 KB/s)
pkgs/main/linux-64       [=>              ] (00m:00s) 240 KB / ?? (789.60 KB/s)
pkgs/main/noarch         [<=>                 ] (00m:00s)
pkgs/r/linux-64          [=>              ] (00m:00s) 232 KB / ?? (767.62 KB/s)
pkgs/r/noarch            [=>              ] (00m:00s) 232 KB / ?? (765.53 KB/s)
pkgs/main/linux-64       [=>              ] (00m:00s) 240 KB / ?? (789.60 KB/s)
pkgs/main/noarch         [=>              ] (00m:00s) 248 KB / ?? (814.89 KB/s)
pkgs/r/linux-64          [=>              ] (00m:00s) 232 KB / ?? (767.62 KB/s)
pkgs/r/noarch            [=>              ] (00m:00s) 232 KB / ?? (765.53 KB/s)
pkgs/main/linux-64       [=>              ] (00m:00s) 240 KB / ?? (789.60 KB/s)
pkgs/main/noarch         [<=>                 ] (00m:00s) Finalizing...
pkgs/r/linux-64          [=>              ] (00m:00s) 232 KB / ?? (767.62 KB/s)
pkgs/r/noarch            [=>              ] (00m:00s) 232 KB / ?? (765.53 KB/s)
pkgs/main/linux-64       [=>              ] (00m:00s) 240 KB / ?? (789.60 KB/s)
pkgs/main/noarch         [<=>                 ] (00m:00s) Done
pkgs/main/noarch         [====================] (00m:00s) Done
pkgs/r/linux-64          [=>              ] (00m:00s) 232 KB / ?? (767.62 KB/s)
pkgs/r/noarch            [=>              ] (00m:00s) 232 KB / ?? (765.53 KB/s)
pkgs/main/linux-64       [=>              ] (00m:00s) 240 KB / ?? (789.60 KB/s)
pkgs/r/linux-64          [<=>             ] (00m:00s) 232 KB / ?? (767.62 KB/s)
pkgs/r/noarch            [=>              ] (00m:00s) 232 KB / ?? (765.53 KB/s)
pkgs/main/linux-64       [=>              ] (00m:00s) 240 KB / ?? (789.60 KB/s)
pkgs/r/linux-64          [<=>              ] (00m:00s) 1020 KB / ?? (2.20 MB/s)
pkgs/r/noarch            [=>              ] (00m:00s) 232 KB / ?? (765.53 KB/s)
pkgs/main/linux-64       [=>              ] (00m:00s) 240 KB / ?? (789.60 KB/s)
pkgs/r/linux-64          [<=>              ] (00m:00s) 1020 KB / ?? (2.20 MB/s)
pkgs/r/noarch            [=>              ] (00m:00s) 232 KB / ?? (765.53 KB/s)
pkgs/main/linux-64       [<=>             ] (00m:00s) 240 KB / ?? (789.60 KB/s)
pkgs/r/linux-64          [<=>              ] (00m:00s) 1020 KB / ?? (2.20 MB/s)
pkgs/r/noarch            [=>              ] (00m:00s) 232 KB / ?? (765.53 KB/s)
pkgs/main/linux-64       [ <=>                ] (00m:00s) 1 MB / ?? (2.24 MB/s)
pkgs/r/linux-64          [<=>              ] (00m:00s) 1020 KB / ?? (2.20 MB/s)
pkgs/r/noarch            [<=>             ] (00m:00s) 232 KB / ?? (765.53 KB/s)
pkgs/main/linux-64       [ <=>                ] (00m:00s) 1 MB / ?? (2.24 MB/s)
pkgs/r/linux-64          [<=>              ] (00m:00s) 1020 KB / ?? (2.20 MB/s)
pkgs/r/noarch            [ <=>                ] (00m:00s) 1 MB / ?? (2.23 MB/s)
pkgs/main/linux-64       [ <=>                ] (00m:00s) 1 MB / ?? (2.24 MB/s)
pkgs/r/linux-64          [<=>              ] (00m:00s) 1020 KB / ?? (2.20 MB/s)
pkgs/r/noarch            [ <=>                ] (00m:00s) Finalizing...
pkgs/main/linux-64       [ <=>                ] (00m:00s) 1 MB / ?? (2.24 MB/s)
pkgs/r/linux-64          [<=>              ] (00m:00s) 1020 KB / ?? (2.20 MB/s)
pkgs/r/noarch            [ <=>                ] (00m:00s) Done
pkgs/main/linux-64       [ <=>                ] (00m:00s) 1 MB / ?? (2.24 MB/s)
pkgs/r/noarch            [====================] (00m:00s) Done
pkgs/r/linux-64          [<=>              ] (00m:00s) 1020 KB / ?? (2.20 MB/s)
pkgs/main/linux-64       [ <=>                ] (00m:00s) 1 MB / ?? (2.24 MB/s)
pkgs/r/linux-64          [ <=>                ] (00m:00s) Finalizing...
pkgs/main/linux-64       [ <=>                ] (00m:00s) 1 MB / ?? (2.24 MB/s)
pkgs/r/linux-64          [ <=>                ] (00m:00s) Done
pkgs/main/linux-64       [ <=>                ] (00m:00s) 1 MB / ?? (2.24 MB/s)
pkgs/r/linux-64          [====================] (00m:00s) Done
pkgs/main/linux-64       [ <=>                ] (00m:00s) 1 MB / ?? (2.24 MB/s)
pkgs/main/linux-64       [  <=>               ] (00m:00s) 1 MB / ?? (2.24 MB/s)
pkgs/main/linux-64       [  <=>               ] (00m:00s) 2 MB / ?? (3.43 MB/s)
pkgs/main/linux-64       [   <=>              ] (00m:00s) 2 MB / ?? (3.43 MB/s)
pkgs/main/linux-64       [   <=>              ] (00m:00s) 3 MB / ?? (3.76 MB/s)
pkgs/main/linux-64       [    <=>             ] (00m:00s) 3 MB / ?? (3.76 MB/s)
pkgs/main/linux-64       [    <=>             ] (00m:00s) 4 MB / ?? (3.93 MB/s)
pkgs/main/linux-64       [     <=>            ] (00m:00s) 4 MB / ?? (3.93 MB/s)
pkgs/main/linux-64       [     <=>            ] (00m:00s) 4 MB / ?? (4.14 MB/s)
pkgs/main/linux-64       [     <=>            ] (00m:00s) Finalizing...
pkgs/main/linux-64       [     <=>            ] (00m:01s) Done
pkgs/main/linux-64       [====================] (00m:01s) Done

Pinned packages:
  - python 3.7.*


Transaction

  Prefix: /home/jupyterlab/conda/envs/python

  Updating specs:

   - bs4==4.10.0
   - ca-certificates
   - certifi
   - openssl


  Package               Version  Build           Channel                  Size
────────────────────────────────────────────────────────────────────────────────
  Install:
────────────────────────────────────────────────────────────────────────────────

  + bs4                  4.10.0  hd3eb1b0_0      pkgs/main/noarch        10 KB

  Change:
────────────────────────────────────────────────────────────────────────────────

  - openssl              1.1.1s  h0b41bf4_1      installed
  + openssl              1.1.1s  h7f8727e_0      pkgs/main/linux-64       4 MB

  Upgrade:
────────────────────────────────────────────────────────────────────────────────

  - ca-certificates   2022.9.24  ha878542_0      installed
  + ca-certificates  2023.01.10  h06a4308_0      pkgs/main/linux-64     120 KB
  - certifi           2022.9.24  pyhd8ed1ab_0    installed
  + certifi           2022.12.7  py37h06a4308_0  pkgs/main/linux-64     150 KB

  Downgrade:
────────────────────────────────────────────────────────────────────────────────

  - beautifulsoup4       4.11.1  pyha770c72_0    installed
  + beautifulsoup4       4.10.0  pyh06a4308_0    pkgs/main/noarch        85 KB

  Summary:

  Install: 1 packages
  Change: 1 packages
  Upgrade: 2 packages
  Downgrade: 1 packages

  Total download: 4 MB

────────────────────────────────────────────────────────────────────────────────

Downloading  [>                                        ] (00m:00s)   38.05 KB/s
Extracting   [>                                                      ] (--:--)
Finished bs4                                  (00m:00s)              10 KB     39 KB/s
Downloading  [>                                        ] (00m:00s)   38.05 KB/s
Extracting   [>                                                      ] (--:--)
Downloading  [>                                        ] (00m:00s)   38.05 KB/s
Extracting   [>                                                      ] (--:--)
Downloading  [>                                        ] (00m:00s)   38.05 KB/s
Extracting   [>                                                      ] (--:--)
Downloading  [>                                        ] (00m:00s)  351.42 KB/s
Extracting   [>                                                      ] (--:--)
Downloading  [>                                        ] (00m:00s)  351.42 KB/s
Extracting   [========>                                ] (00m:00s)        1 / 5
Finished beautifulsoup4                       (00m:00s)              85 KB    314 KB/s
Downloading  [>                                        ] (00m:00s)  351.42 KB/s
Extracting   [========>                                ] (00m:00s)        1 / 5
Downloading  [>                                        ] (00m:00s)  351.42 KB/s
Extracting   [========>                                ] (00m:00s)        1 / 5
Downloading  [>                                        ] (00m:00s)  351.42 KB/s
Extracting   [========>                                ] (00m:00s)        1 / 5
Downloading  [==>                                      ] (00m:00s)  794.13 KB/s
Extracting   [========>                                ] (00m:00s)        1 / 5
Finished ca-certificates                      (00m:00s)             120 KB    449 KB/s
Downloading  [==>                                      ] (00m:00s)  794.13 KB/s
Extracting   [========>                                ] (00m:00s)        1 / 5
Downloading  [==>                                      ] (00m:00s)  794.13 KB/s
Extracting   [========>                                ] (00m:00s)        1 / 5
Downloading  [===>                                     ] (00m:00s)    1.31 MB/s
Extracting   [========>                                ] (00m:00s)        1 / 5
Finished certifi                              (00m:00s)             150 KB    560 KB/s
Downloading  [===>                                     ] (00m:00s)    1.31 MB/s
Extracting   [========>                                ] (00m:00s)        1 / 5
Downloading  [===>                                     ] (00m:00s)    1.31 MB/s
Extracting   [========>                                ] (00m:00s)        1 / 5
Downloading  [===>                                     ] (00m:00s)    1.31 MB/s
Extracting   [========>                                ] (00m:00s)        1 / 5
Downloading  [===>                                     ] (00m:00s)    1.31 MB/s
Extracting   [================>                        ] (00m:00s)        2 / 5
Downloading  [=========================>               ] (00m:00s)    8.02 MB/s
Extracting   [================>                        ] (00m:00s)        2 / 5
Downloading  [=========================>               ] (00m:00s)    8.02 MB/s
Extracting   [================>                        ] (00m:00s)        2 / 5
Downloading  [=========================>               ] (00m:00s)    8.02 MB/s
Extracting   [========================>                ] (00m:00s)        3 / 5
Downloading  [=========================>               ] (00m:00s)    8.02 MB/s
Extracting   [========================>                ] (00m:00s)        3 / 5
Downloading  [=========================>               ] (00m:00s)    8.02 MB/s
Extracting   [================================>        ] (00m:00s)        4 / 5
Downloading  [=========================================] (00m:00s)   11.34 MB/s
Extracting   [================================>        ] (00m:00s)        4 / 5
Finished openssl                              (00m:00s)               4 MB     11 MB/s
Downloading  [=========================================] (00m:00s)   11.34 MB/s
Extracting   [================================>        ] (00m:00s)        4 / 5
Downloading  [=========================================] (00m:00s)   11.34 MB/s
Extracting   [================================>        ] (00m:00s)        4 / 5
Downloading  [=========================================] (00m:00s)   11.34 MB/s
Extracting   [================================>        ] (00m:00s)        4 / 5
Downloading  [=========================================] (00m:00s)   11.34 MB/s
Extracting   [=========================================] (00m:00s)        5 / 5
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Collecting lxml==4.6.4
  Downloading lxml-4.6.4-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (6.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 46.0 MB/s eta 0:00:0000:0100:01
Installing collected packages: lxml
  Attempting uninstall: lxml
    Found existing installation: lxml 4.9.1
    Uninstalling lxml-4.9.1:
      Successfully uninstalled lxml-4.9.1
Successfully installed lxml-4.6.4

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.15.3) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['html5lib==1.1']

pkgs/main/linux-64       Using cache
pkgs/main/noarch         Using cache
pkgs/r/linux-64          Using cache
pkgs/r/noarch            Using cache

Pinned packages:
  - python 3.7.*


Transaction

  Prefix: /home/jupyterlab/conda/envs/python

  Updating specs:

   - html5lib==1.1
   - ca-certificates
   - certifi
   - openssl


  Package         Version  Build         Channel                 Size
───────────────────────────────────────────────────────────────────────
  Install:
───────────────────────────────────────────────────────────────────────

  + html5lib          1.1  pyhd3eb1b0_0  pkgs/main/noarch       91 KB
  + webencodings    0.5.1  py37_1        pkgs/main/linux-64     19 KB

  Summary:

  Install: 2 packages

  Total download: 110 KB

───────────────────────────────────────────────────────────────────────

Downloading  [>                                        ] (00m:00s)    3.43 KB/s
Extracting   [>                                                      ] (--:--)
Downloading  [>                                        ] (00m:00s)    3.43 KB/s
Extracting   [>                                                      ] (--:--)
Downloading  [======>                                  ] (00m:00s)  127.35 KB/s
Extracting   [>                                                      ] (--:--)
Finished webencodings                         (00m:00s)              19 KB    124 KB/s
Downloading  [======>                                  ] (00m:00s)  127.35 KB/s
Extracting   [>                                                      ] (--:--)
Downloading  [======>                                  ] (00m:00s)  127.35 KB/s
Extracting   [>                                                      ] (--:--)
Downloading  [======>                                  ] (00m:00s)  127.35 KB/s
Extracting   [>                                                      ] (--:--)
Downloading  [=========================================] (00m:00s)  700.11 KB/s
Extracting   [>                                                      ] (--:--)
Finished html5lib                             (00m:00s)              91 KB    577 KB/s
Downloading  [=========================================] (00m:00s)  700.11 KB/s
Extracting   [>                                                      ] (--:--)
Downloading  [=========================================] (00m:00s)  700.11 KB/s
Extracting   [>                                                      ] (--:--)
Downloading  [=========================================] (00m:00s)  700.11 KB/s
Extracting   [====================>                    ] (00m:00s)        1 / 2
Downloading  [=========================================] (00m:00s)  700.11 KB/s
Extracting   [====================>                    ] (00m:00s)        1 / 2
Downloading  [=========================================] (00m:00s)  700.11 KB/s
Extracting   [=========================================] (00m:00s)        2 / 2
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

### Importing the required modules and functions

In [2]:
from bs4 import BeautifulSoup # this module helps in web scrapping.
import requests  # this module helps us to download a web page

<h2 id="BSO">Beautiful Soup Objects</h2>

Beautiful Soup is a Python library for pulling data out of HTML and XML files, I will focus on HTML files. This is accomplished by representing the HTML as a set of objects with methods used to parse the HTML.

To parse a document, pass it into the <code>BeautifulSoup</code> constructor, the <code>BeautifulSoup</code> object, which represents the document as a nested data structure:

<h2 id="DSCW">Downloading And Scraping The Contents Of A Web Page</h2>

We Download the contents of the web page:

In [70]:
url = "http://www.ibm.com"

We use <code>get</code> to download the contents of the webpage in text format and store in a variable called <code>data</code>:

In [71]:
data  = requests.get(url).text

We create a <code>BeautifulSoup</code> object using the <code>BeautifulSoup</code> constructor

In [72]:
soup = BeautifulSoup(data,"html.parser")  # create a soup object using the variable 'data'

Scrape all links

In [73]:
for link in soup.find_all('a',href=True):  # in html anchor/link is represented by the tag <a>

    print(link.get('href'))

https://www.ibm.com/thought-leadership/institute-business-value/en-us/report/business-trends-2023
#ibm-hp--tech-section
https://www.ibm.com/consulting/?lnk=ushpv18intro2
https://www.ibm.com/about
https://www.ibm.com/consulting/?lnk=flathl
https://www.ibm.com/consulting/strategy/?lnk=flathl
https://www.ibm.com/consulting/ibmix?lnk=flathl
https://www.ibm.com/consulting/technology/
https://www.ibm.com/consulting/operations/?lnk=flathl
https://www.ibm.com/strategic-partnerships
https://www.ibm.com/employment/?lnk=flatitem
https://www.ibm.com/impact
https://research.ibm.com/
https://www.ibm.com/

## Scrape  all images  Tags

In [74]:
for link in soup.find_all('img'):# in html image is represented by the tag <img>
    print(link)
    print(link.get('src'))

<img alt="Person standing with arms crossed" aria-describedby="bx--image-1" class="bx--image__img" src="https://1.dam.s81c.com/p/0a23e414312bcb6f/08196d0e04260ae5_cropped.jpg.global.sr_16x9.jpg"/>
https://1.dam.s81c.com/p/0a23e414312bcb6f/08196d0e04260ae5_cropped.jpg.global.sr_16x9.jpg
<img alt="Team members at work in a conference room" aria-describedby="bx--image-2" class="bx--image__img" src="https://1.dam.s81c.com/p/06655c075aa3aa29/CaitOppermann_2019_12_06_IBMGarage_DSC3304.jpg.global.m_16x9.jpg"/>
https://1.dam.s81c.com/p/06655c075aa3aa29/CaitOppermann_2019_12_06_IBMGarage_DSC3304.jpg.global.m_16x9.jpg
<img alt="Coworkers looking at laptops" aria-describedby="bx--image-3" class="bx--image__img" src="https://1.dam.s81c.com/p/08f951353c2707b8/052022_CaitOppermann_InsideIBM_London_2945_03.jpg.global.sr_16x9.jpg"/>
https://1.dam.s81c.com/p/08f951353c2707b8/052022_CaitOppermann_InsideIBM_London_2945_03.jpg.global.sr_16x9.jpg
<img alt="Cloud developer with red sweater coding at desk" aria-describedby="bx--image-4" class="bx--image__img" src="https://1.dam.s81c.com/p/064e0139f5a3aa5e/0500002_Lowell_LI_100119.jpg.global.sr_16x9.jpg"/>
https://1.dam.s81c.com/p/064e0139f5a3aa5e/0500002_Lowell_LI_100119.jpg.global.sr_16x9.jpg
<img alt="Aerial view of automated conveyer belt and machinery at work" aria-describedby="bx--image-5" class="bx--image__img" src="https://1.dam.s81c.com/p/0795cae91a25156f/conveyorrobottopview.jpg.global.sr_16x9.jpg"/>
https://1.dam.s81c.com/p/0795cae91a25156f/conveyorrobottopview.jpg.global.sr_16x9.jpg
<img alt="Overhead view of partners collaborating on design with laptops and coffee" aria-describedby="bx--image-6" class="bx--image__img" src="https://1.dam.s81c.com/p/06dfa9ccdba4ec79/1f417900-9042-44d1-9c219a854bbb62ea.jpg.global.sr_16x9.jpg"/>
https://1.dam.s81c.com/p/06dfa9ccdba4ec79/1f417900-9042-44d1-9c219a854bbb62ea.jpg.global.sr_16x9.jpg

### find all

The find_all() method looks through a tag’s descendants and retrieves all descendants that match your filters.

The Method signature for find_all(name, attrs, recursive, string, limit, **kwargs)

## Scrape data from HTML tables

In [79]:
#The below url contains an html table with data about colors and color codes.
url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DA0321EN-SkillsNetwork/labs/datasets/HTMLColorCodes.html"

Before proceeding to scrape a web site, you need to examine the contents, and the way data is organized on the website. Open the above url in your browser and check how many rows and columns are there in the color table.

In [80]:
# get the contents of the webpage in text format and store in a variable called data
data  = requests.get(url).text

In [81]:
soup = BeautifulSoup(data,"html.parser")

In [1]:
#find a html table in the web page
table = soup.find('table') # in html table is represented by the tag <table>

NameError: name 'soup' is not defined

In [83]:
#Get all rows from the table
for row in table.find_all('tr'): # in html table row is represented by the tag <tr>
    # Get all columns in each row.
        cols = row.find_all('td') # in html a column is represented by the tag <td>
    color_name = cols[2].string # store the value in column 3 as color_name
    color_code = cols[3].string # store the value in column 4 as color_code
    print("{}--->{}".format(color_name,color_code))

Color Name--->None
lightsalmon--->#FFA07A
salmon--->#FA8072
darksalmon--->#E9967A
lightcoral--->#F08080
coral--->#FF7F50
tomato--->#FF6347
orangered--->#FF4500
gold--->#FFD700
orange--->#FFA500
darkorange--->#FF8C00
lightyellow--->#FFFFE0
lemonchiffon--->#FFFACD
papayawhip--->#FFEFD5
moccasin--->#FFE4B5
peachpuff--->#FFDAB9
palegoldenrod--->#EEE8AA
khaki--->#F0E68C
darkkhaki--->#BDB76B
yellow--->#FFFF00
lawngreen--->#7CFC00
chartreuse--->#7FFF00
limegreen--->#32CD32
lime--->#00FF00
forestgreen--->#228B22
green--->#008000
powderblue--->#B0E0E6
lightblue--->#ADD8E6
lightskyblue--->#87CEFA
skyblue--->#87CEEB
deepskyblue--->#00BFFF
lightsteelblue--->#B0C4DE
dodgerblue--->#1E90FF

## Scrape data from HTML tables into a DataFrame using BeautifulSoup and Pandas

In [84]:
import pandas as pd

In [86]:
#The below url contains html tables with data about world population.
url = "https://en.wikipedia.org/wiki/World_population"

Before proceeding to scrape a web site, we need to examine the contents, and the way data is organized on the website. The above url was used in checking the tables on the webpage.

In [87]:
# get the contents of the webpage in text format and store in a variable called data
data  = requests.get(url).text

In [88]:
soup = BeautifulSoup(data,"html.parser")

In [89]:
#find all html tables in the web page
tables = soup.find_all('table') # in html table is represented by the tag <table>

In [90]:
# we can see how many tables were found by checking the length of the tables list
len(tables)

24

Assuming we are looking for the `10 most densly populated countries` table, we can look through the tables list and find the right one we are looking for based on the data in each table or we can search for the table name if it is in the table but this option might not always work.

In [91]:
for index,table in enumerate(tables):
    if ("10 most densely populated countries" in str(table)):
        table_index = index
print(table_index)

4

Below we used the prettify method of beautiful soup to locate the table name of the table, `10 most densly populated countries`

In [92]:
print(tables[table_index].prettify())

<table class="wikitable sortable" style="text-align:right">
 <caption>
  10 most densely populated countries
  <small>
   (with population above 5 million)
  </small>
  <sup class="reference" id="cite_ref-:10_107-0">
   <a href="#cite_note-:10-107">
    [102]
   </a>
  </sup>
 </caption>
 <tbody>
  <tr>
   <th scope="col">
    Rank
   </th>
   <th scope="col">
    Country
   </th>
   <th scope="col">
    Population
   </th>
   <th scope="col">
    Area
    <br/>
    <small>
     (km
     <sup>
      2
     </sup>
     )
    </small>
   </th>
   <th scope="col">
    Density
    <br/>
    <small>
     (pop/km
     <sup>
      2
     </sup>
     )
    </small>
   </th>
  </tr>
  <tr>
   <td>
    1
   </td>
   <td align="left">
    <span class="flagicon">
     <img alt="" class="thumbborder" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Singapore.svg/23px-Flag_of_Singapore.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Singapore.svg/35px-Flag_of_Singapore.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Singapore.svg/45px-Flag_of_Singapore.svg.png 2x" width="23"/>
    </span>
    <a href="/wiki/Singapore" title="Singapore">
     Singapore
    </a>
   </td>
   <td>
    5,921,231
   </td>
   <td>
    719
   </td>
   <td>
    8,235
   </td>
  </tr>
  <tr>
   <td>
    2
   </td>
   <td align="left">
    <span class="flagicon">
     <img alt="" class="thumbborder" data-file-height="600" data-file-width="1000" decoding="async" height="14" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Flag_of_Bangladesh.svg/23px-Flag_of_Bangladesh.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Flag_of_Bangladesh.svg/35px-Flag_of_Bangladesh.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Flag_of_Bangladesh.svg/46px-Flag_of_Bangladesh.svg.png 2x" width="23"/>
    </span>
    <a href="/wiki/Bangladesh" title="Bangladesh">
     Bangladesh
    </a>
   </td>
   <td>
    165,650,475
   </td>
   <td>
    148,460
   </td>
   <td>
    1,116
   </td>
  </tr>
  <tr>
   <td>
    3
   </td>
   <td align="left">
    <p>
     <span class="flagicon">
      <img alt="" class="thumbborder" data-file-height="216" data-file-width="432" decoding="async" height="12" src="//upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Palestine.svg/23px-Flag_of_Palestine.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Palestine.svg/35px-Flag_of_Palestine.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Palestine.svg/46px-Flag_of_Palestine.svg.png 2x" width="23"/>
     </span>
     <a href="/wiki/State_of_Palestine" title="State of Palestine">
      Palestine
     </a>
     <sup class="reference" id="cite_ref-108">
      <a href="#cite_note-108">
       [103]
      </a>
     </sup>
    </p>
   </td>
   <td>
    5,223,000
   </td>
   <td>
    6,025
   </td>
   <td>
    867
   </td>
  </tr>
  <tr>
   <td>
    4
   </td>
   <td align="left">
    <span class="flagicon">
     <img alt="" class="thumbborder" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/7/72/Flag_of_the_Republic_of_China.svg/23px-Flag_of_the_Republic_of_China.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/7/72/Flag_of_the_Republic_of_China.svg/35px-Flag_of_the_Republic_of_China.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/7/72/Flag_of_the_Republic_of_China.svg/45px-Flag_of_the_Republic_of_China.svg.png 2x" width="23"/>
    </span>
    <a href="/wiki/Taiwan" title="Taiwan">
     Taiwan
    </a>
   </td>
   <td>
    23,580,712
   </td>
   <td>
    35,980
   </td>
   <td>
    655
   </td>
  </tr>
  <tr>
   <td>
    5
   </td>
   <td align="left">
    <span class="flagicon">
     <img alt="" class="thumbborder" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/23px-Flag_of_South_Korea.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/35px-Flag_of_South_Korea.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/45px-Flag_of_South_Korea.svg.png 2x" width="23"/>
    </span>
    <a href="/wiki/South_Korea" title="South Korea">
     South Korea
    </a>
   </td>
   <td>
    51,844,834
   </td>
   <td>
    99,720
   </td>
   <td>
    520
   </td>
  </tr>
  <tr>
   <td>
    6
   </td>
   <td align="left">
    <span class="flagicon">
     <img alt="" class="thumbborder" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/5/59/Flag_of_Lebanon.svg/23px-Flag_of_Lebanon.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/5/59/Flag_of_Lebanon.svg/35px-Flag_of_Lebanon.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/5/59/Flag_of_Lebanon.svg/45px-Flag_of_Lebanon.svg.png 2x" width="23"/>
    </span>
    <a href="/wiki/Lebanon" title="Lebanon">
     Lebanon
    </a>
   </td>
   <td>
    5,296,814
   </td>
   <td>
    10,400
   </td>
   <td>
    509
   </td>
  </tr>
  <tr>
   <td>
    7
   </td>
   <td align="left">
    <span class="flagicon">
     <img alt="" class="thumbborder" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/1/17/Flag_of_Rwanda.svg/23px-Flag_of_Rwanda.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/1/17/Flag_of_Rwanda.svg/35px-Flag_of_Rwanda.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/1/17/Flag_of_Rwanda.svg/45px-Flag_of_Rwanda.svg.png 2x" width="23"/>
    </span>
    <a href="/wiki/Rwanda" title="Rwanda">
     Rwanda
    </a>
   </td>
   <td>
    13,173,730
   </td>
   <td>
    26,338
   </td>
   <td>
    500
   </td>
  </tr>
  <tr>
   <td>
    8
   </td>
   <td align="left">
    <span class="flagicon">
     <img alt="" class="thumbborder" data-file-height="600" data-file-width="1000" decoding="async" height="14" src="//upload.wikimedia.org/wikipedia/commons/thumb/5/50/Flag_of_Burundi.svg/23px-Flag_of_Burundi.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/5/50/Flag_of_Burundi.svg/35px-Flag_of_Burundi.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/5/50/Flag_of_Burundi.svg/46px-Flag_of_Burundi.svg.png 2x" width="23"/>
    </span>
    <a href="/wiki/Burundi" title="Burundi">
     Burundi
    </a>
   </td>
   <td>
    12,696,478
   </td>
   <td>
    27,830
   </td>
   <td>
    456
   </td>
  </tr>
  <tr>
   <td>
    9
   </td>
   <td align="left">
    <span class="flagicon">
     <img alt="" class="thumbborder" data-file-height="900" data-file-width="1350" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/23px-Flag_of_India.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/35px-Flag_of_India.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/45px-Flag_of_India.svg.png 2x" width="23"/>
    </span>
    <a href="/wiki/India" title="India">
     India
    </a>
   </td>
   <td>
    1,389,637,446
   </td>
   <td>
    3,287,263
   </td>
   <td>
    423
   </td>
  </tr>
  <tr>
   <td>
    10
   </td>
   <td align="left">
    <span class="flagicon">
     <img alt="" class="thumbborder" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/23px-Flag_of_the_Netherlands.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/35px-Flag_of_the_Netherlands.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/45px-Flag_of_the_Netherlands.svg.png 2x" width="23"/>
    </span>
    <a href="/wiki/Netherlands" title="Netherlands">
     Netherlands
    </a>
   </td>
   <td>
    17,400,824
   </td>
   <td>
    41,543
   </td>
   <td>
    419
   </td>
  </tr>
 </tbody>
</table>

In [93]:
population_data = pd.DataFrame(columns=["Rank", "Country", "Population", "Area", "Density"])

for row in tables[table_index].tbody.find_all("tr"):
    col = row.find_all("td")
    if (col != []):
        rank = col[0].text
        country = col[1].text
        population = col[2].text.strip()
        area = col[3].text.strip()
        density = col[4].text.strip()
        population_data = population_data.append({"Rank":rank, "Country":country, "Population":population, "Area":area, "Density":density}, ignore_index=True)

population_data

  Rank                Country     Population       Area Density
0    1              Singapore      5,921,231        719   8,235
1    2             Bangladesh    165,650,475    148,460   1,116
2    3  \n Palestine[103]\n\n      5,223,000      6,025     867
3    4                 Taiwan     23,580,712     35,980     655
4    5            South Korea     51,844,834     99,720     520
5    6                Lebanon      5,296,814     10,400     509
6    7                 Rwanda     13,173,730     26,338     500
7    8                Burundi     12,696,478     27,830     456
8    9                  India  1,389,637,446  3,287,263     423
9   10            Netherlands     17,400,824     41,543     419

## Scrape data from HTML tables into a DataFrame using BeautifulSoup and read_html

Using the same `url`, `data`, `soup`, and `tables` object as in the last section we can use the `read_html` function to create a DataFrame.

The table we need is located in `tables[table_index]`

We can now use the `pandas` function `read_html` and give it the string version of the table as well as the `flavor` which is the parsing engine `bs4`.

In [94]:
pd.read_html(str(tables[5]), flavor='bs4')

[   Rank         Country  Population  Area(km2)  Density(pop/km2)  \
 0     1           India  1389637446    3287263               423
 1     2        Pakistan   242923845     796095               305
 2     3      Bangladesh   165650475     148460              1116
 3     4           Japan   124214766     377915               329
 4     5     Philippines   114597229     300000               382
 5     6         Vietnam   103808319     331210               313
 6     7  United Kingdom    67791400     243610               278
 7     8     South Korea    51844834      99720               520
 8     9          Taiwan    23580712      35980               655
 9    10       Sri Lanka    23187516      65610               353

   Population trend[citation needed]
 0                           Growing
 1                   Rapidly growing
 2                   Rapidly growing
 3                    Declining[104]
 4                           Growing
 5                           Growing
 6                           Growing
 7                            Steady
 8                            Steady
 9                           Growing  ]

The function `read_html` always returns a list of DataFrames so we must pick the one we want out of the list.

In [95]:
population_data_read_html = pd.read_html(str(tables[5]), flavor='bs4')[0]

population_data_read_html

,Rank,Country,Population,Area(km2),Density(pop/km2),Population trend[citation needed]
0,1,India,1389637446,3287263,423,Growing
1,2,Pakistan,242923845,796095,305,Rapidly growing
2,3,Bangladesh,165650475,148460,1116,Rapidly growing
3,4,Japan,124214766,377915,329,Declining[104]
4,5,Philippines,114597229,300000,382,Growing
5,6,Vietnam,103808319,331210,313,Growing
6,7,United Kingdom,67791400,243610,278,Growing
7,8,South Korea,51844834,99720,520,Steady
8,9,Taiwan,23580712,35980,655,Steady
9,10,Sri Lanka,23187516,65610,353,Growing

## Scrape data from HTML tables into a DataFrame using read_html

We can also use the `read_html` function to directly get DataFrames from a `url`.

In [96]:
dataframe_list = pd.read_html(url, flavor='bs4')

We can see there are 25 DataFrames just like when we used `find_all` on the `soup` object.

In [97]:
len(dataframe_list)

24

Finally we can pick the DataFrame we need out of the list.

In [98]:
dataframe_list[5]

,Rank,Country,Population,Area(km2),Density(pop/km2),Population trend[citation needed]
0,1,India,1389637446,3287263,423,Growing
1,2,Pakistan,242923845,796095,305,Rapidly growing
2,3,Bangladesh,165650475,148460,1116,Rapidly growing
3,4,Japan,124214766,377915,329,Declining[104]
4,5,Philippines,114597229,300000,382,Growing
5,6,Vietnam,103808319,331210,313,Growing
6,7,United Kingdom,67791400,243610,278,Growing
7,8,South Korea,51844834,99720,520,Steady
8,9,Taiwan,23580712,35980,655,Steady
9,10,Sri Lanka,23187516,65610,353,Growing

We can also use the `match` parameter to select the specific table we want. If the table contains a string matching the text it will be read.

In [99]:
pd.read_html(url, match="10 most densely populated countries", flavor='bs4')[0]

   Rank         Country  Population  Area(km2)  Density(pop/km2)
0     1       Singapore     5921231        719              8235
1     2      Bangladesh   165650475     148460              1116
2     3  Palestine[103]     5223000       6025               867
3     4          Taiwan    23580712      35980               655
4     5     South Korea    51844834      99720               520
5     6         Lebanon     5296814      10400               509
6     7          Rwanda    13173730      26338               500
7     8         Burundi    12696478      27830               456
8     9           India  1389637446    3287263               423
9    10     Netherlands    17400824      41543               419